name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          submodules: false  # Отключаем подмодули

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Check artifact size
        run: |
          cd site
          echo "Checking artifact size..."
          du -sh .
          echo "Checking for symlinks..."
          find . -type l -print

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: site/
          retention-days: 1  # Уменьшаем срок хранения

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: github-pages
          timeout: 60000